name: check-code

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python 3.11.6 with pip cache
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.6
        cache: pip

    - name: Run pre-commit on all files
      uses: pre-commit/action@v3.0.0
